# Generated by Django 4.0.4 on 2022-05-09 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RealEstateApp', '0003_alter_property_author_mostviewed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=250)),
                ('contact_number', models.BigIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='user/images/')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RealEstateApp.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
