# Generated by Django 4.0.4 on 2022-05-10 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('AdminUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminuserroles',
            name='roles',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='auth.permission'),
        ),
    ]
