# Generated by Django 4.0.4 on 2022-05-18 05:55

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('AdminUser', '0002_alter_adminuserroles_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularLocations',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=250, null=True)),
                ('state', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
                ('popular_rank', models.IntegerField(null=True)),
            ],
        ),
    ]
