# Generated by Django 4.0.4 on 2022-05-05 07:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RealEstateApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=100)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=30)),
                ('nationality', django_countries.fields.CountryField(blank=True, max_length=2)),
                ('email', models.EmailField(max_length=50)),
                ('mobile_Number', models.BigIntegerField()),
                ('date_from', models.DateTimeField()),
                ('date_until', models.DateTimeField()),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('booking_status', models.CharField(choices=[('initiated', 'Initiated'), ('pending', 'Pending'), ('confirm', 'Confirm'), ('cancel', 'Cancel'), ('completed', 'Completed')], default='initiated', max_length=100)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('notes', models.TextField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RealEstateApp.address')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RealEstateApp.property')),
            ],
        ),
    ]
