# Generated by Django 4.0.4 on 2022-05-10 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mobile_number', models.BigIntegerField(null=True)),
                ('messages', models.TextField(null=True)),
            ],
        ),
    ]
