# Generated by Django 4.0.4 on 2022-05-10 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0002_booking_paid_booking_slug_booking_updated_date'),
        ('BookingApp', '0002_contact'),
    ]

    operations = [
    ]
