# Generated by Django 4.0.4 on 2022-05-07 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RealEstateApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='created',
            new_name='created_date',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='updated',
            new_name='updated_date',
        ),
        migrations.AddField(
            model_name='property',
            name='author',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='property/images/'),
        ),
    ]
