# Generated by Django 4.0.4 on 2022-05-07 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RealEstateApp', '0002_rename_created_property_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MostViewed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('viewed', models.BigIntegerField()),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_property', to='RealEstateApp.property')),
            ],
        ),
    ]
