# Generated by Django 4.0.4 on 2022-05-09 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstateApp', '0003_alter_property_author_mostviewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='landmark',
            new_name='state',
        ),
    ]
