# Generated by Django 4.0.4 on 2022-05-09 11:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RealEstateApp', '0007_alter_property_description_feedbackproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingProperty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=250)),
                ('rank', models.IntegerField(blank=True, default=1, null=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RealEstateApp.property')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ranking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
