# Generated by Django 4.0.4 on 2022-05-16 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstateApp', '0008_rankingproperty'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesProperty',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='property/item/images/')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RealEstateApp.property')),
            ],
        ),
    ]
