# Generated by Django 4.0.4 on 2022-06-06 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstateApp', '0009_imagesproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedbackproperty',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imagesproperty',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rankingproperty',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=5),
            preserve_default=False,
        ),
    ]
