# Generated by Django 4.0.4 on 2022-06-06 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RealEstateApp', '0010_address_created_date_feedbackproperty_created_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='feedbackproperty',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='imagesproperty',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='rankingproperty',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='room',
            name='created_date',
        ),
    ]
